title: Jose A Bauza
logo: /assets/img/headshot_circle.jpeg
description: Dynamic Business Professional
show_downloads: false
theme: jekyll-theme-minimal
# linkedin_url: https://www.linkedin.com/in/jose-bauza/
