title: Jose A Bauza
logo: /assets/img/headshot_sq.png
description: Dynamic Business Professional with a robust background in data analytics, data engineering, and data science. 
show_downloads: false
theme: jekyll-theme-minimal
# linkedin_url: https://www.linkedin.com/in/jose-bauza/
